- .travis.yml
- Cargo.toml
- blacklist.txt
- ci/install.sh
- ci/script.sh
- src/cfail.rs
- src/lib.rs
- src/ring_buffer/mod.rs
- src/ring_buffer/spsc.rs
- tests/tsan.rs
> use atomics where available

- src/vec.rs
Semantics are the same as their equivalents in std::vec::Vec.
> Add methods Vec::resize() and Vec::resize_default()

- src/lib.rs
- src/ring_buffer/mod.rs
Resolves #6 
Refactor the ring_buffer::{Iter,IterMut} implementations to use a macro, so there is less duplicate code.
Inspired by the[ slice iterator macro in lib core](https://github.com/rust-lang/rust/blob/master/src/libcore/slice/mod.rs).
I have never worked with macros to generate const / mut implementations.
So this might be a little rough.
`#![allow(stable_features)]` is needed for current rust nightly, since otherwise `conservative_impl_trait` would throw a warning. Removing the feature flag would not be backwards compatible with earlier nightly versions.
> Ringbuffer iterators macro

- src/vec.rs
~~This implementation uses vec::reverse and vec::pop to move the content of the vector out of it.~~
It might give more performance to avoid the `reverse` and read each element individually. In the end  the unmoved items need to be dropped.
> Implement IntoIter for Vec

- src/vec.rs
As discussed in #36 
Panics when the vector can not hold all values supplied by the iterator.
Calling `unwrap` on the result might not be the best choice here.
It might be better to match the result and have a custom panic message.
Is this the best possible behavior?
> Implement FromIterator for Vec

- src/ring_buffer/mod.rs
- tests/tsan.rs
When the head index becomes greater than the tail, the `len()` function returns the incorrect length. This causes iterations over ring buffers to stop early as well, since they use the same calculation.
This PR adds two (very minimal) tests that demonstrate the error.
> Fix incorrect length calculation for RingBuffer when head > tail

- Cargo.toml
- ci/script.sh
- src/__core.rs
- src/binary_heap.rs
- src/const_fn.rs
- src/lib.rs
- src/linear_map.rs
- src/ring_buffer/mod.rs
- src/ring_buffer/spsc.rs
- src/string.rs
- src/vec.rs
- tests/tsan.rs
This PR introduces the `const-fn` feature gate, which when enabled makes most `new` methods `const` 
and therefore usable for initializing `static` variables.
The idea was introduced in #40 with the purpose to come closer to targeting stable rust.
`const` functions are currently only available on rust nightly (tracking issue: [const fn tracking issue (RFC 911)](https://github.com/rust-lang/rust/issues/24111)).
In order to target stable rust this feature is made opt-in.
This feature is a **breaking change** as users of the library now need to explicitly enable it by changing their `Cargo.toml`:
```
...
[dependencies]
heapless = { version = "0.4.0", features = ["const-fn"] }
...
```
The implementation of the feature mainly consist of the `const_fn!` macro, which takes a function with …
> Put all const functions behind a const-fn feature

- Cargo.toml
- src/lib.rs
- src/ring_buffer/mod.rs
- src/ring_buffer/spsc.rs
> RingBuffer: put smaller atomic indices behind a Cargo feature

- src/__core.rs
- src/ring_buffer/mod.rs
- src/ring_buffer/spsc.rs
- src/vec.rs
which has been proposed in rust-lang/rfcs#1892
closes #51 
closes #52 
closes #53
> internally use MaybeUninit

- src/binary_heap.rs
- src/linear_map.rs
- src/spsc/mod.rs
As pointed out in #56 the `fmt::Debug` implementation for those types is missing.
This PR implements them by passing their respective `Iterator` to the formatter.
- Should `Debug` also be implemented for `spsc::Consumer` and `spsc::Producer`?
- Should the implementation for `BinaryHeap` respect the priority of the items in the heap?
> Implement Debug for `Queue`, `LinearMap` and `BinaryHeap`

- Cargo.toml
- build.rs
- src/const_fn.rs
- src/lib.rs
- src/pool/mod.rs
- src/pool/singleton.rs
- src/string.rs
this adds the stable subset of the `lifo::Pool` [1] API
[1]: https://github.com/japaric/lifo
> add lock-free, interrupt-safe memory pool

- src/__core.rs
to not cause UB when unoptimized
appears to fix japaric/cortex-m-rtfm#182
> tweak crate::MaybeUninit::unitialized

- src/binary_heap.rs
- src/de.rs
- src/sealed.rs
- src/ser.rs
- src/spsc/mod.rs
- src/spsc/split.rs
resolves #72
breaking change, since a previously public trait is now private
> Turn `binary_heap::Kind` into a sealed trait

- build.rs
on nightly (rustc 1.37.0-nightly (7840a0b75 2019-05-31)) the build is currently broken (see below).
Adding `dyn Error` as the error result in `build.rs` solves the problem.
```
$ cargo +nightly build      
Compiling typenum v1.10.0
Compiling stable_deref_trait v1.1.1
Compiling byteorder v1.2.7
Compiling heapless v0.5.0-alpha.2 (/home/felix/workspace/rust/heapless)
error: trait objects without an explicit `dyn` are deprecated
--> build.rs:5:29
|
5 | fn main() -> Result<(), Box<Error>> {
|                             ^^^^^ help: use `dyn`: `dyn Error`
|
note: lint level defined here
--> build.rs:1:9
|
1 | #![deny(warnings)]
|         ^^^^^^^^
= note: #[deny(bare_trait_objects)] implied by #[deny(warnings)]
error: aborting due to previous error
error: Could not compile `heapless`.
warning: …
```
> Fix boxed Error in build.rs for nightly

- .travis.yml
This PR enables CI runs for Rust 1.36 and current stable for on Ci branches for bors.
> Enable MSRV 1.36 for travis-ci

- src/spsc/mod.rs
In both cases, head is subtracted from tail, wrapping when necessary.
> Remove unecessary conditional

- .travis.yml
- build.rs
- src/pool/mod.rs
- src/pool/singleton.rs
> Added armv8 support

- src/string.rs
This commit handles a new rustc warning currently in nightly.
I think this is why #129 failed. 🙂
> remove unnecessary parentheses

- src/sealed.rs
- src/spsc/mod.rs
This will lead to implausibly large lengths, nearly endless iterators
and possibly unsound behaviour through the Drop implementation
Switches the `truncate` method to refer to the common defintion of
simply chopping of the test bits. (Implemented by `as`, which is defined
to do this).
Adds a new `saturate` method to replace the previous `truncate` method
> Fix improper handling of overflow in `len_usize` (fix #128)

- src/de.rs
The maps are already being serialized as maps, and serde_json will detect
that despite us claiming that maps are seqs, it falls back to parsing them
as maps; however, serde-json-core does not have that fallback logic, so it
makes more sense to give the correct hint here (especially when this is
merged: https://github.com/japaric/serde-json-core/pull/23)
> Deserialize maps as maps

- CHANGELOG.md
- Cargo.toml
- build.rs
The built-in rustc targets ended with names that start with `armv7a-` so #140
does not cover them though the intention was to support them; this commit fixes
that
> Extend the ARMv7-A `Pool` support to the bare-metal `armv7a-` targets.

- CHANGELOG.md
- src/pool/mod.rs
- src/pool/singleton.rs
There was a discussion in the riot channel about what it's needed for a buffer to be DMA safe, where ra_kete came up with this POC:
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=339a9a29fb59c080b42b6d77a902acb6
Where it seems that the requirements described in the [Embedonomicon](https://docs.rust-embedded.org/embedonomicon/dma.html#static-bound) doesn't seem to be enough to prevent stack corruption.
If that is really the case and we decide to use `StableDeref` instead, then a implementation for Box is very important to be able to easily use it on DMA APIs and a new point release would be necessary.
CC @korken89
> Implement StableDeref for singleton::Box

- src/histbuf.rs
- src/lib.rs
- tests/cpass.rs
Closes #112
Unfortunately `const` construction won't work since the `Default` or `Clone` bound on `T` can't be used then, so I've not added an internal type to `i.rs`.
Let me know if you think any other traits should be implemented...
> add the HistoryBuffer type

- src/vec.rs
Implementation mostly copied from `std`.
The logic should be covered by documentation tests, so no separate unit tests were added.
> Implement Vec::starts_with and Vec::ends_with

- Cargo.toml
- src/lib.rs
- src/ufmt.rs
By enabling the `ufmt-impl` feature, `uWrite` impls are provided for `String<N>` and `Vec<u8, N>`.
> Add optional ufmt impls

- build.rs
Extends support for singleton `Pool`s to include the `armebv7r-none-eabi` and `armebv7r-none-eabihf` targets.
> Extend ARMv7-R `Pool` support to the bare-metal `armebv7r-` targets

- src/vec.rs
I didn't see a mention of this in issues or previous pull requests, but I expect it's in scope?
> Implement core::fmt::Write for heapless::Vec<u8, N>

- Cargo.toml
- ci/script.sh
- src/lib.rs
- src/pool/cas.rs
- src/pool/llsc.rs
- src/pool/mod.rs
- src/pool/singleton.rs
- tests/tsan.rs
this PR makes `Pool` `Sync` on x86_64 with the main goal of being able to test `no_std` code that uses `Pool` (e.g. via the singleton `pool!` macro) on x86_64 (as it's not straight forward to run tests on embedded devices, and even less to CI those tests).
this PR reduces the chance of Pool running into the ABA problem (which corrupts the underlying lock-free stack) by using 32-bit version tags (search term: IBM ABA-prevention tags). Version tags do not 100% prevent the ABA problem but make it almost impossible to run into it in practice (the bigger the tag, in bits, the less the chance of running into ABA). See module level docs for details and limitations.
As this does not eliminate ABA with 100% certainty perhaps it should live behind a Cargo feature?
It seems to me that hazard …
> x86_64: "practically" thread-safe  Pool

- src/spsc/split.rs
I assume there's no reason that only multi-core Producers are marked
Send, while Consumers are not (they're pretty symmetrical).
(Context: I'm trying to use an SPSC queue on a single cortex-m0 MCU.
So I can guarantee that a SingleCore queue is safe because there is no
other core it could possibly be shared with.  The RTFM framework adds
an assert_send on the producer, since it's shared between init and an
SPI receiver interrupt.  It also adds an assert_send on the Consumer,
since it's shared between init and the I2C transmit interrupt, but that one
works since Consumer has this extra C type in the impl already.)
> Make Producer<..., SingleCore> Send, like Consumer

- src/lib.rs
This change allows the create custom structs based on `IndexMap` with size arguments outside
the heapless crate itself.
For example:
```rust
use heapless::consts::*;
use heapless::{ArrayLength, Bucket, FnvIndexMap, Pos, PowerOfTwo};
struct CustomMap<S>
where
S: ArrayLength<Bucket<u8, u16>> + ArrayLength<Option<Pos>> + PowerOfTwo,
{
map: FnvIndexMap<u8, u16, S>,
}
impl<S> CustomMap<S>
where
S: ArrayLength<Bucket<u8, u16>> + ArrayLength<Option<Pos>> + PowerOfTwo,
{
fn new() -> CustomMap<S> {
CustomMap {
map: FnvIndexMap::<_, _, S>::new(),
}
}
}
fn main() {
let mut bla = CustomMap::<U8>::new();
bla.map.insert(8, 16).unwrap();
}
```
I can imagine that exposing these types is not preferable, but at least it would help for my usecase. Or is there a way where exposing these types is not needed?
> indexmap: expose PowerOfTwo, Bucket and Pos

- src/histbuf.rs
STM32G081 Cortex-M0 64MHz
thumbv6m-none-eabi
Rust 1.43.1
RTFM application where data from ADC channels is added to `HistoryBuffers`:
```Rust
// this is shared with DMA
static mut ADC_DATA: [u16; 6] = [0; 6];
...
// this interrupt fires when DMA has finished sequencing all ADC channels
#[task(binds = DMA_CHANNEL1, resources = [pa9, adc_data, hist0, hist1, hist2, hist3, hist4, hist5])]
fn adc_data_ready(ctx: adc_data_ready::Context) {
let dma = unsafe { &(*stm32::DMA::ptr()) };
// transfer complete flag clear
dma.ifcr.write(|w| w.ctcif1().set_bit());
ctx.resources.pa9.set_high().unwrap();
ctx.resources.hist0.write(ctx.resources.adc_data[0]);
ctx.resources.hist1.write(ctx.resources.adc_data[1]);
ctx.resources.hist2.write(ctx.resources.adc_data[2]); …
```
> histbuf: replace slow modulo operations

- src/string.rs
- src/vec.rs
This adds `set_len` to `Vec`, identical to the `std` version, with the documentation copied from `std`. This is useful for using it as a buffer by writing to the uninitialized portion and then setting the length to include those bytes.
It also adds `as_mut_vec` to `String` (also from `std`), which enables using `String` as a buffer in the same manner.
> Buffer methods for Vec and as_mut_vec for String

- Cargo.toml
This fixes the issue I was having targeting AVR.
See: https://github.com/japaric/heapless/issues/177#issuecomment-697341580
```
(base) ~/temp/break/abc $ cargo build
Updating crates.io index
Compiling compiler_builtins v0.1.35
Compiling core v0.0.0 (/home/todd/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core)
Compiling typenum v1.12.0
Compiling version_check v0.9.2
Compiling byteorder v1.3.4
Compiling heapless v0.5.6 (/home/todd/temp/heapless)
Compiling generic-array v0.14.4
Compiling rustc-std-workspace-core v1.99.0 (/home/todd/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/rustc-std-workspace-core)
Compiling stable_deref_trait v1.2.0
Compiling hash32 v0.1.1
Compiling generic-array v0.12.3
Compiling generic-array …
```
> Version bump dependency 'as-slice' -> 0.1.4

- src/spsc/split.rs
This PR exposes `capacity` and `len` for The `Consumer` and `Producer` which were not available in either of those after split.
> Queue: Expose len and capacity for Consumer and Producer

- src/indexmap.rs
- src/indexset.rs
in our embedded workshops we tripped over the Example for IndexMap using FNVIndexMap, but `FNVIndexMap` having no example or explan ation for this. Especially when youre in a hurry or new to Rust, it's easy to miss what's going on. This PR is an attempt to clarify this in the docs and copy examples to concrete instantiations of `IndexMap` and `IndexSet`.
I hope I got the wording right, "instantiation" doesn't seem like the exactly right word to describe whats going on...
> IndexMap, IndexSet: hint to FnvIndex...: Extend explanation, add examples & links

- .github/workflows/build.yml
Needed for full GHA functionality together with Bors
See [here](https://github.com/bors-ng/bors-ng/issues/1129) for details on the Bors change.
RTIC project among others faced the same issue
> Remove GHA ci-failure job

- CHANGELOG.md
- Cargo.toml
En attendant `min_const_generics` :)
Fixes the UB reported in https://github.com/fizyk20/generic-array/issues/97.
Thanks to https://github.com/fizyk20/generic-array/pull/102, the MSRV remains the same, 1.36.0.
Closes https://github.com/japaric/heapless/issues/166.
> Bump generic-array to v0.14.2 (MSRV remains the same)

- Cargo.toml
Resolves RUSTSEC-2020-0145
https://github.com/RustSec/advisory-db/pull/779
> Update generic-array and as-slice to security patched versions

- src/mpmc.rs
This p-r adds a new test case `full_at_wrapped_pos0`, which went into infinite loop. This p-r fixes the problem by using `i8` (instead of `i16`) to calculate the `dif` (`seq - pos` in `enqueue`, `seq - (pos + 1)` in `dequeue`).
The root cause of this problem was basically the same as #121: when the `pos` goes beyond 255, it wraps back to 0 because `pos` is in `u8`. When the `u8` wrapping occurs, the sign of `dif` becomes inverse, which caused the problem.
Using `i8` for `dif` fixes the problem, because even when the `u8` wrapping occurs, the `dif` is wrapped again in `i8`, so we get the right sign for `dif`. `i8` only allows values in [-127, 128], but `|dif|` is at most the size of the queue. The size of the queue is at most 64 in this library, so it's no problem.
This p-r removes the fix …
> mpmc: use i8 to calculate dif to deal with u8 wrapping

- Cargo.toml
- src/mpmc.rs
Current MPMC has a very limited size set. This PR makes it generic over different sizes.
The PR also preserves the current behavior with U8 as max size. This should be completely backward compatible. 
There is also an alternative with Usized size which doesn't have the limitation on the number of elements. This can be enabled by the `mpmc_large` feature flag.
> Generic MPMC

- Cargo.toml
- src/defmt.rs
- src/lib.rs
This PR adds support for encoding `heapless::Vec` for usage with `defmt`.
`defmt` can already handle slices, so this impl simply invokes that encoder method.
I chose to use the slice implementation is I did not perceive the difference between a Vec and a Slice to be of specific importance in a log file, but rather the contents of the vec / slice to be of interest. It also appeared to me as the path of least resistance.
I am marking this as a draft as I have yet to be able to validate this against my local hardware, `probe-run` is giving me some grief that I am reasonably sure is unrelated to this change set. 
Relates to #171
> defmt impl for Vec

- src/spsc.rs
`capacity` is defined as `N - 1`. But best performance (cheap modulo) is achieved if `N` is a power of two, not `capacity`.
This fixes the docstring.
> spsc: fix optimal queue size docstring

- Cargo.toml
... otherwise any crate using heapless will automatically add all the
funny ARMv6-M only dependencies regardless.
Signed-off-by: Daniel Egger <daniel@eggers-club.de>
> Make "atomic-polyfill" an optional dep for thumbv6m-none-eabi only

- src/string.rs
- src/vec.rs
As described in the subject. These were missing and are otherwise implemented by the standard library.
> Add PartialOrd and Ord to Vec and String

- CHANGELOG.md
- src/deque.rs
- src/lib.rs
- src/vec.rs
This PR adds a heapless `Deque` struct. which is the heapless equivalent of the good old [`VecDeque`](https://doc.rust-lang.org/std/collections/struct.VecDeque.html).
This is different from the MPMC/SPSC `Queue`s. This does not aim to be lock-free. All mutating operations require `&mut self`. This allows for much more functionality, such as pushing/popping from both front and back, iterating the contents (even mutably), etc.
> Add Deque.

- src/pool/mod.rs
the logic was increasing the "capacity" counter even in the case the given memory address was out of
range (ANCHOR +- 2GB) -- `None` branch in code -- resulting in a wrong / misleading value being
reported
> fix return value of `Pool::grow` on x86_64

- .github/workflows/build.yml
- Cargo.toml
- src/pool/cas.rs
- src/pool/mod.rs
- src/pool/singleton.rs
the implementation uses a 64-bit atomic on `x86` to avoid the `ANCHOR` variable and the address
space limitation seen with the x86_64 compilation target
this PR also adds the i686-linux-musl target to the test matrix to exercise the new implementation
closes #231
> Sync Pool support for (32-bit) x86

- src/lib.rs
- src/pool/singleton.rs
- src/pool/singleton/arc.rs
Like `std::sync::Arc` but backed by a memory pool (just like `heapless::Box`). The memory pool (singleton) is defined using the `arc_pool!` macro.
The [`Weak`](https://doc.rust-lang.org/std/sync/struct.Arc.html#method.downgrade) API is not included with this PR, but it could be added in the future if desired.
> add Arc pointer backed by a memory pool

- src/deque.rs
- src/spsc.rs
- tests/tsan.rs
- Fix 2 miri errors in `Deque`
- Ignore a few tests that take way too long in miri (gave up after waiting 5+ min)
> Miri fixes

- src/pool/cas.rs
- src/pool/mod.rs
- src/pool/singleton.rs
closes #239 
see individual commit messages and code comments for details
the second commit fixes an actual bug (grow API was doing something when the data was ZST; the intention was that to be a no-op but the check was wrong). the other 2 commit make miri not complain when dealing with ZSTs
it would be good to test the arc pool with ZST and run miri again; it may need the same treatment as the box pool
r? @korken89 
cc @Dirbaio
> fix miri errors

- src/vec.rs
There already is the `Vec::from_slice` method that does the same, but implementing the `TryFrom` trait makes it easier to write code that works both with `heapless::Vec` and `std::vec::Vec`.
> Implement TryFrom<&[T]> for Vec<T, N>

- src/sealed.rs
- src/vec.rs
Use when building generated code where it's possible to have a zero
length array/vector (e.g. wire-format). See #252
- Added vec::tests::zero_capacity test
- Added sealed::greater_than_eq_0
> Relax Vec bounds to allow for zero-length Vecs

- CHANGELOG.md
- src/histbuf.rs
- src/lib.rs
My use case requires an oldest..newest iterator. I tried https://github.com/japaric/heapless/pull/253 but ran into a crash when the buffer was empty (len = 0).
This PR:
- fixes the crash when len is 0
- adds more test cases
- addresses https://github.com/japaric/heapless/pull/253#issuecomment-1012914870
> Feature/historybuf `OldestOrdered` iterator

- CHANGELOG.md
- Cargo.toml
- build.rs
- src/mpmc.rs
- src/pool/llsc.rs
- src/pool/mod.rs
- src/pool/singleton/arc.rs
- src/spsc.rs
I at first was only going to fix the documentation for `pool` and `mpmc`, clarifying that `thumbv6m` in fact _does_ include these modules via the `atomic-polyfill` crate, but then noticed that we could add the two `riscv` targets as they also have `atomic-polyfill` support as of `v0.1.4`. `MSP430` does not have support at this time.
> Add cas support for risc-v via atomic-polyfill and fix mpmc/pool documentation

- CHANGELOG.md
- Cargo.toml
I have an M1 Mac so the x86 specific test prevented me from running `cargo test`. I'm not sure why `scoped_threadpool` isn't just a plain old [`dev-dependency]` though... should I just make it an unqualified `[dev-dependency]` instead?
> assume native compilation if target_os is not "none" to allow non-x86 hosts to run tests

- Cargo.toml
- build.rs
- suppressions.txt
- tests/tsan.rs
as it's easier to deal with TSAN false positives in the former API
as it surfaced in PR #280 the current supression rules don't handle newer versions of the
`scoped_threadpool` crate
trying to update the supression rules related to `scoped_threadpool` in PR #282 revealed that the
supression rules are masking (hiding) real data races:
https://github.com/japaric/heapless/pull/282#issuecomment-1113173358
`std::thread::scope` requires less supression rules and does not mask real data races -- for instance,
the data race in the linked issue comment is not masked when using `std::thread::scope`
tradeoffs:
- pro: one less dev dependency but added a small build dependency
- pro: supressions file is simpler
- cons: `std::thread::scope` is only available on recent nightlies but the API is only used …
> use std::thread::scope instead of scoped_threadpool

- CHANGELOG.md
- src/binary_heap.rs
- src/vec.rs
Hi! We ran into an exception triggered by new undefined behavior checks inserted into the nightly compiler (https://github.com/rust-lang/rust/pull/92686/files#diff-54110dcedc5a4d976321aa5d2a6767ac0744a3ef1363b75ffc62faf81cf14c30R230-L229). Running `heapless`'s test suite under Miri didn't flag anything at first, but it did once we added `MIRIFLAGS="-Zmiri-tag-raw-pointers"`. All three of the fixes in this PR were identified via
```
MIRIFLAGS="-Zmiri-tag-raw-pointers -Zmiri-ignore-leaks" cargo +nightly miri test -- --skip pool::
```
and the fixes came from copying the implementations from the equivalent methods in `std`. Note that I skipped the `pool::` tests; there is at least one miri failure in them, but it wasn't immediately obvious how to fix it so I skipped it for now. It's probably …
> Fix undefined behavior identified by Miri

- CHANGELOG.md
- src/binary_heap.rs
- src/lib.rs
- src/test_helpers.rs
- src/vec.rs
Vec's destructor already takes cares of calling the elements' destructors
> fix: BinaryHeap elements are dropped twice

- src/binary_heap.rs
- src/deque.rs
- src/test_helpers.rs
- src/vec.rs
it's safe to assume that test platforms have CAS operations available
> remove unsafe from Droppable test helper

- CHANGELOG.md
- src/sorted_linked_list.rs
In order to support AVR, the following changes were made:
- AVR was added to the list of architectures not supporting atomics or cas.
- AVR was configured to not use AtomicUsize, similarly to armv6m.
- SortedLinkedList was modified to account for the fact that usize is differently sized on
different architectures (16 bits on AVR).
> Add support for AVR.

- CHANGELOG.md
- src/vec.rs
these changes optimize `Vec<u8, 1024>::clone` down to these operations
1. reserve the stack space (1028 bytes on 32-bit ARM) and leave it uninitialized
2. zero the `len` field
3. memcpy `len` bytes of data from the parent
analyzed source code
``` rust
use heapless::Vec;
fn clone(vec: &Vec<u8, 1024>) {
let mut vec = vec.clone();
black_box(&mut vec);
}
fn black_box<T>(val: &mut T) {
unsafe { asm!("// {0}", in(reg) val) }
}
```
machine code with `lto = fat`, `codegen-units = 1` and `opt-level = 'z'` ('z' instead of 3 to avoid loop unrolling and keep the machine code readable)
``` armasm
00020100 <clone>:
20100:              b5d0             push    {r4, r6, r7, lr}
20102:              af02             add     r7, sp, #8
20104:              f5ad 6d81        sub.w   sp, sp, #1032   ; 0x408 …
```
> optimize the codegen of Vec::clone

- .github/workflows/build.yml
- CHANGELOG.md
- Cargo.toml
due to a limitation in the llvm backend [1] the `riscv32i-unknown-none-elf` target lacks the `core::sync::atomic` API even though the actual hardware is capable of atomic loads and stores (`fence` instruction). thus, at this point in time, this target needs `atomic-polyfill` for a working SPSC implementation
[1]: https://github.com/knurling-rs/defmt/issues/597#issuecomment-934467023
fixes #271 
closes #272 
closes #273
> unconditionally depend on atomic-polyfill for riscv32i target

- src/binary_heap.rs
std::collections::BinaryHeap provides an into_vec method https://doc.rust-lang.org/std/collections/struct.BinaryHeap.html#method.into_vec
My use case is I want a sorted iterator  similar to BinaryHeap.into_sorted_iter. I found my self creating a new heapless:Vec from heapless::BinaryHeap::into_iter and then sorting it. It seemed better to return the underlying vec and sort that.
But the functionality seemed generally useful and helps the API jive a little better with std::collections::BinaryHeap.
Do you see any issues with this implementation? Also, apologies for anything weird... This is my first PR :)
> add BinaryHeap::into_vec

- CHANGELOG.md
- src/indexmap.rs
closes #295
I tested this manually with both `FnvIndexSet` and `FnvIndexMap`. I tried to add a compile fail test but discovered (the hard way) that all the const assert trickery in `sealed` is checked when the code is built with `cargo build` but *not* when the code is built with `cargo check`. As `trybuild` uses `cargo check` under the hood it's not possible to compile fail test any of those const asserts.
r? @korken89
> compile-time check power of two invariant in Index{Set,Map}'s default method

- CHANGELOG.md
- Cargo.toml
- build.rs
- src/sorted_linked_list.rs
This patch includes changes I needed to build my Arduino Uno sketches.  I incorporated the work from https://github.com/japaric/heapless/pull/264 to reduce the chance of conflicts.
Now that atomic-polyfill 0.1.8 supports AVR, things are a bit easier.
> Add support for Arduino Uno and 2560

- CHANGELOG.md
- src/vec.rs
Added
- `Vec::insert(index, element)`
- `Vec::remove(index)`
- `Vec::retain(f)`
- `Vec::retain_mut(f)`
Behavior matches `std` except `insert` which is now fallible and returns back the element when full. Implementation and docs taken from `std`.
> Add some more Vec methods.

- src/string.rs
Needed to look into implementation to be sure String was allocating bytes not chars.
> Add clarification in String

- src/vec.rs
I was using the Vec for tests and initially, I was confused because I saw the impl for PartialEq but then I realized that PartialEq with Rhs of Vec was not implemented.
These impls are not mandatory but might help other people when using Vec on Rhs.
PS: Amazing crate btw, thanks you for the awesome work!
> Vec - PartialEq where Rhs is the Vec

- CHANGELOG.md
- src/mpmc.rs
- src/pool/mod.rs
- src/spsc.rs
- src/vec.rs
Turns out there were some broken links and `#![deny(warnings)]` in the crate root.
> Make the docs build

- .github/workflows/build.yml
it seems runners are assigned to jobs in the order they appear in the
yaml file. miri takes the longest so it's better if it appears first
> ci: run miri tests first

- CHANGELOG.md
- Cargo.toml
- src/de.rs
- src/indexmap.rs
- src/indexset.rs
- src/ser.rs
- src/spsc.rs
- src/string.rs
- src/vec.rs
this release of `hash32` has the advantage that 32-bit hashers can be used to hash types that
implement the `core::hash::Hash` trait removing the need for the `hash32::Hash` implementations in
this crate and the uses of the `#[derive(Hash32)]` macro (which did not support enums) in dependent
crates
with this change the following code works
``` rust
// NOTE no derive(Hash32)
#[derive(Hash)]
struct Int(i32);
let mut x = FnvIndexSet::<_, 4>::default();
let _ = x.insert(Int(0));
```
this change is technically a breaking change because the following code is no longer accepted
``` rust
// assume this type comes from a dependency
// NOTE no derive(Hash)
#[derive(Hash32)]
struct Int(i32);
let mut x = FnvIndexSet::<_, 4>::default();
let _ = x.insert(Int(0)); // error: does not implement Hash
```
> [breaking-change] use hash32 v0.3.0

- src/indexmap.rs
by making some "exhaustive" tests less exhaustive
> speed up cargo miri test

- CHANGELOG.md
- src/histbuf.rs
- `impl Clone for HistoryBuffer`
- `impl PartialEq for HistoryBuffer`
Both are tested fairly rigorously.
Motivation is to use this type in a `yew::Properties` struct, which requires both traits to be implemented.
> impl {Clone, PartialEq} for HistoryBuffer {...}

- CHANGELOG.md
- src/indexmap.rs
- src/indexset.rs
Some requirements are not necessary and the specification can be removed/simplified. This makes these types a bit more ergonomic when using them in a trait or function definition as not all traits need to be specified for some cases.
> Relax trait requirements on IndexMap/IndexSet.

- CHANGELOG.md
- src/indexmap.rs
- src/indexset.rs
- src/lib.rs
Exports the `Iter` types for `IndexSet` and `IndexMap`.
My use case is having a trait generic over a `BTreeSet` and `IndexSet` which has a `type Iter`.
> Export Iter from IndexSet and IndexMap

- CHANGELOG.md
- src/histbuf.rs
This method returns the contents of a HistoryBuffer as two ordered slices, similar to [Deque::as_slices()](https://docs.rs/heapless/0.7.16/heapless/struct.Deque.html#method.as_slices).
> Add HistoryBuffer::as_slices()

- CHANGELOG.md
- src/pool/boxed.rs
- src/pool/object.rs
I add ReadBuffer and WriteBuffer to pool::object::Object and pool::box::Box.
It allows to use embedded DMA of HAL crates, such as [stm32f4xx_hal::dma::Transfer](https://docs.rs/stm32f4xx-hal/latest/stm32f4xx_hal/dma/struct.Transfer.html).
> Recover StableDeref trait for pool::object::Object and pool::boxed::Box

- Cargo.toml
This updates `spin` to the newest version, this change helps us in one of our repos.
> Update spin dependency to newer version

- CHANGELOG.md
- src/indexmap.rs
- src/lib.rs
Exports all the iterator types of `IndexMap`.
I wonder if it'd make sense to have a module structure such as the one in `alloc::collections`, e.g.: `heapless::indexmap` and re-export `heapless::indexmap::IndexMap` on the crate root, to have all the iterator types inside the `indexmap` module but still public.
> export all IndexMap iterators

- .github/workflows/build.yml
- CHANGELOG.md
- cfail/ui/freeze.stderr
- cfail/ui/not-send.stderr
- src/linear_map.rs
Please do review this carefully.  I'm not confident this (the fix and the test) is correct.  Note there is `unsafe` in `impl Drop for Vec` which is the backend data structure for `LinearMap`.
A couple CI failures will still occur, see #387.
> Fix dropping_references warning

- build.rs
Fixes #349
Alternatively we could change the probe to something like:
```rust
#[no_mangle]
pub unsafe fn probe(x: &usize, y: usize) -> usize {
let mut ret;
asm!(
"       clrex",
"2:",
"       ldrex {2}, [{0}]",
"       strex {tmp}, {1}, [{0}]",
"       cmp {tmp}, #0",
"       bne 2b",
in(reg) x,
in(reg) y,
out(reg) ret,
tmp = out(reg) _,
);
ret
}
```
Without explicitly denying any `aarch64*` target.
> Fix pool (mis)compile on AArch64

- .github/workflows/build.yml
- CHANGELOG.md
- Cargo.toml
- build.rs
- src/mpmc.rs
- src/spsc.rs
I intend to deprecate `atomic-polyfill` soon, in favor of `portable-atomic`. It supports more archs and is more actively maintained. ~The only thing it can't do yet is use `critical-section`, but it should soon~ it already can: https://github.com/taiki-e/portable-atomic/pull/51
> Use `portable-atomic` instead of `atomic-polyfill`.

- .github/workflows/build.yml
I was wondering why the merge queue was awfully quick.
> CI: add build.yml to merge group

- CHANGELOG.md
- src/string.rs
Closes #378
Leverages the error type from [`core::str::from_utf8`](https://doc.rust-lang.org/std/str/fn.from_utf8.html), but it takes a `heapless::Vec` as an argument similar to [`core::String::from_utf8`](https://doc.rust-lang.org/beta/alloc/string/struct.String.html#method.from_utf8) to avoid allocation errors.
I figured we may as well add the `unsafe` version too for completeness.
> String: add from_utf8

- .github/workflows/build.yml
- CHANGELOG.md
- src/de.rs
- src/indexmap.rs
- src/ser.rs
- src/string.rs
Sorry for mixing unrelated stuff, I merged an unrebased PR which made CI tests fail after merging, and didn't notice because the merge queue wasn't configured yet. After merging this I'll configure it, now that this simplifies CI a bit so that there's lesa less ridiculous amount of jobs.
#361 rebased
closes #360 
closes #361
> Fix IndexMap entry API, fix CI.

- CHANGELOG.md
- src/vec.rs
It is already available through `DerefMut` so making it public doesn't do any harm and makes using slice mut methods a little bit clearer. For example:
`(&mut s[..]).get_mut(i)` vs `s.as_mut_slice().get_mut(i)`
> Make Vec::as_mut_slice public

- src/vec.rs
All values of `usize` are `>= 0` by definition.
> Vec: remove do-nothing assertion

- CHANGELOG.md
- Cargo.toml
Configures the `stable_deref_trait` to only be included for `arm_llsc` and `target_arch = "x86"` platforms. This is because the dependency is only used for the `pool` module, and the `pool` module is only used on the above platforms.
Reduces the dependency graph for all other platforms.
> deps: make `stable_deref_trait` an optional dependency

- .github/workflows/build.yml
- CHANGELOG.md
- src/binary_heap.rs
- src/deque.rs
- src/histbuf.rs
- src/indexmap.rs
- src/linear_map.rs
- src/mpmc.rs
- src/pool/arc.rs
- src/sealed.rs
- src/sorted_linked_list.rs
- src/spsc.rs
- src/string.rs
- src/vec.rs
- tests/tsan.rs
> Fix clippy lints

- src/linear_map.rs
- src/mpmc.rs
- mpmc: use cmp() as per clippy
- linear_map: use binding ergonomics, adress clippy
c.f. #411
> clippy lint in mpmc and linear_map

- .github/workflows/build.yml
- rustfmt.toml
- src/binary_heap.rs
- src/defmt.rs
- src/deque.rs
- src/histbuf.rs
- src/indexmap.rs
- src/indexset.rs
- src/lib.rs
- src/sorted_linked_list.rs
- src/spsc.rs
- src/vec.rs
This is a nightly feature, but I have used it in other repositories for >1 year without issues.
Related to #411
> rustfmt: run on doc comments

- .github/workflows/build.yml
- src/pool/boxed.rs
- src/spsc.rs
- src/string.rs
- src/vec.rs
- tests/tsan.rs
> Run clippy on tests

- src/pool/boxed.rs
> boxed: suppress clippy lint in doctest

- src/lib.rs
This section is no longer comprehensive.
These features are already documented in `Cargo.toml`, and I'm not a huge fan of duplicating documentation.
> lib.rs: remove Optional Features section

- CHANGELOG.md
- src/lib.rs
- src/string.rs
Motivation:
If you want to create a formatted `heapless::String` at the moment, it is necessary to create a mutable string and modify it:
```rust
let mut string = heapless::String::<10>::new();
write!(&mut string, "{:>3}cm", height).unwrap();
```
It's a bit nicer to have a `format!` macro that constructs the `String` in-place without requiring an intermediate step, just as Rust's standard library offers.
```rust
let string = format!(10, "{:>3}cm", height);
```
> add format macro implementation

- CHANGELOG.md
- src/pool/boxed.rs
> Add test for box_pool with CamelCase types

- CHANGELOG.md
- src/binary_heap.rs
- src/indexmap.rs
- src/indexset.rs
- src/lib.rs
- src/linear_map.rs
- src/mpmc.rs
- src/pool.rs
- src/sorted_linked_list.rs
- src/spsc.rs
- src/string.rs
- src/vec.rs
Add equivalent to `std::string::String::from_utf16` and additional `push_utf16` helper method.
> Add `String::from_utf16`.

- src/linear_map.rs
> LinearMap: Fix false-positive clippy lint

- src/histbuf.rs
This is a separate PR because I prefer adding tests separately from features that may cause them to fail.
> HistoryBuffer: add drop test for clear

- CHANGELOG.md
- src/sealed.rs
- src/vec.rs
This PR implements conversion from arrays to vec. The array does not have to be the same length as the capacity of the vec. Const generics are asserted at compile time. Unfortunately the method currently requires a copy of the source array.
Partially addresses requests in #341 and #344.
Also I'm not totally happy about the const assertions given #351. I've not added any tests in the `cfail` suite as I don't think we can practically check this with `trybuild` at the moment. There is a bit of a work-around you can do but it's not pretty.
1. Would we prefer to just implement `From<[T; N]> for Vec<T, N>`? One of the issues with this impl is that users will need to be explicit about vec capacity. Because lengths `N` and `M` can be different, you can't write:
```rust
let v = Vec::from([1, 2, …
```
> Impl conversion from array to Vec

- CHANGELOG.md
- src/lib.rs
Adds `Deque`, `HistoryBuffer` and `SortedLinkedList` to the list of implemented data structures in the crate docs. The current list of items seems to be only a subset what's actually been implemented.
> Add missing entries to list of implemented data structures in crate docs.

- .github/workflows/build.yml
- src/lib.rs
We already pass `--deny warnings` to `clippy`.
> Only deny warnings in CI.

- CHANGELOG.md
- src/deque.rs
Adds `Deque::make_contiguous` based on [`VecDeque::make_contiguous`](https://doc.rust-lang.org/std/collections/struct.VecDeque.html#method.make_contiguous) in the std library.
Implementation derived from [here](https://github.com/rust-lang/rust/blob/0b7730105fb7e008002f6ba29f87a55699f67744/library/alloc/src/collections/vec_deque/mod.rs#L2160).
This method provides a contiguous mutable slice to a `Deque`, allowing slice methods like `sort` to be used.
> Adds `Deque::make_contiguous`

- CHANGELOG.md
- cfail/ui/not-send.stderr
- src/lib.rs
- src/vec.rs
Alternative approach to #424, with even better ergonomics and features, but slightly more confusing documentation.
```rust
use heapless::{Vec, VecView};
let mut vec: Vec<u8, 10> = Vec::from_slice(&[1, 2, 3, 4]).unwrap();
// No const-generic on the view, and `&Vec` coerces to `&VecView` through unsize coercion 
let view: &VecView<u8> = &vec;
assert_eq!(view, &[1, 2, 3, 4]);
// No const-generic on the view, and `&mut Vec` coerces to `&mut VecView` through unsize coercion 
let mut_view: &mut VecView<u8> = &mut vec;
mut_view.push(5);
assert_eq!(vec, [1, 2, 3, 4, 5]);
```
This approach is more "scalable" in the sense that using it means that other structures that use a `Vec` internally can also have a `View` type that is simply the `!Sized` version of the same structure. This would be useful …
> Vec: add a "View" that can mutate the vec and erase the const generic.

- CHANGELOG.md
- src/pool.rs
- src/pool/arc.rs
- src/pool/boxed.rs
- src/pool/object.rs
The `allow` attributes are not needed:
The static variable defined in the `singleton` method is never exposed, so the name doesn't need to be the same as the pool.
The name of the struct should simply follow the standard naming conventions, the examples have been updated to make this clear this should be PascalCase.
Properly fixes https://github.com/rust-embedded/heapless/issues/411 and https://github.com/rust-embedded/heapless/issues/454.
> Fix pool macro warnings.

- CHANGELOG.md
- Cargo.toml
- src/lib.rs
- src/pool/arc.rs
- src/pool/treiber.rs
- src/pool/treiber/cas.rs
- src/pool/treiber/llsc.rs
Closes https://github.com/rust-embedded/heapless/issues/421.
> Implement `pool` for any 32/64-bit architecture that supports the corresponding atomics.

- CHANGELOG.md
- src/mpmc.rs
Fixes https://github.com/rust-embedded/heapless/issues/461.
> Fix `MpMcQueue` with `mpmc_large` feature.

- src/vec.rs
Reduce duplicated code by implementing traits for `Vec` and `VecView` using macros.
Also add `inline` to functions that redirect to `VecView`.
> Use macros to implement traits for `Vec` and `VecView`.

- CHANGELOG.md
- src/linear_map.rs
This PR implements the `IntoIterator` trait for `LinearMap`.
It uses the existing `linear_map::IntoIter` struct as the return type which was previously unused.
A test case has been added.
Closes #472
> Implement IntoIterator for LinearMap

- src/vec.rs
In the initial implementation, I implemented `Drop` for `Vec` but I implemented it as a `no-op` for `VecView`, thinking that it should only be dropped through `Vec`.
This is incorrect, `VecView` can be responsible for dropping its content when its owned, for example in a `Box`.
This PR adds a test that fails with the current implementation, showing the memory leak, and fixes it by implementing `Drop` properly for `VecView`
> VecView: fix memory leak of drop

- src/defmt.rs
- src/lib.rs
- src/ser.rs
- src/storage.rs
- src/ufmt.rs
- src/vec.rs
I'm a bit concerned about the code duplication introduced by #425. Most `Vec`
methods forward to their `VecView` counterparts, but the function signature
and the doc comments are still duplicated. This means every time we do a doc
fix or add a new method we have to remember to do it on both sides.
It has worked fine for for experimenting and proving the concept. However,
now we're at a stage where it's proven and we have to commit to
add it to all the other containers: #452 #459 #479 #480 #481 #485.
Each of these PRs adds 400-600 lines to the codebase, mostly duplicated
signatures and docs.
IMO we should find a way of adding `View` types without so much duplication
first, *then* add it to all containers.
This PR implements a possible solution I've found that removes all the duplication:
- …
> vec: remove code duplication due to VecView.

- CHANGELOG.md
- src/mpmc.rs
> Fix memory leak of `MpMcQueue`

- CHANGELOG.md
- src/deque.rs
Adds direct indexing methods to `Deque`, equivalent to their `VecDeque` counterparts.
> Add `Deque::{get, get_mut, get_unchecked, get_unchecked_mut}`

- CHANGELOG.md
- src/lib.rs
- src/slice.rs
- src/string/drain.rs
- src/string/mod.rs
- src/vec/drain.rs
- src/vec/mod.rs
Closes https://github.com/rust-embedded/heapless/issues/334 and https://github.com/rust-embedded/heapless/pull/365.
> Add `Vec::drain` and `String::drain`.

- CHANGELOG.md
- src/histbuf.rs
Rewrite Iterator for OldestOrdered and add DoubleEndedIterator
implementation.
Update HistoryBuffer oldest_ordered() to reflect changes.
> histbuf: Implement DoubleEndedIterator for OldestOrdered

- CHANGELOG.md
- src/indexmap.rs
It would be nice to have some methods for `Entry` like std HashMap [`Entry`](https://doc.rust-lang.org/std/collections/hash_map/enum.Entry.html#implementations) so that developer can using chained method calls.
> Add std `Entry` methods to indexmap `Entry`

- CHANGELOG.md
- src/defmt.rs
- src/ser.rs
- src/string/drain.rs
- src/string/mod.rs
- src/ufmt.rs
If #486 is merged, this would supersede https://github.com/rust-embedded/heapless/pull/452
> String: implement `StringView` on top of #486

- CHANGELOG.md
- src/mpmc.rs
- src/storage.rs
This would supersede #484. We need to pay attention to the `Drop` impl depending on the order we merge PRs
This adds a couple of methods to the `Storage` sealed trait to deal with the fact that `Borrow` cannot be used in concurrent code:
- One to safely get the length of the buffer from a pointer to it
- One to get a pointer to the beginning of the slice
>  `MpMcQueue`: add `MpMcQueueView`, similar to `VecView` on top of #486

- CHANGELOG.md
- src/histbuf.rs
- src/lib.rs
- src/ser.rs
`OldestOrdered` was already part of the public API.
When merging we will need to add its removal to #494 so that there is only `OldestOrederedView` (which can be renamed to just `OldestOrdered`)
> Implement HistoryBufferView on top of #486

- CHANGELOG.md
- src/deque.rs
- src/lib.rs
- src/ser.rs
Efforts have been made to avoid breaking changes:
- Since `capacity` and `len` were `const`, they have been kept on `Deque`, and the generic version on `DequeInner` are prefixed by `storage` and are not `const`
- `Iter<'a, T, const N: usize>` is kept, and a new `IterView` type is added with conversions to and from both iter types. (I also simplified significantly the implementation of the `Iterator`, by using the standard library's iterator combinators).
By accepting a backward incompatible change, these APIs could be made more intuitive.
> Implement DequeView on top of #486

- CHANGELOG.md
- src/sorted_linked_list.rs
Like the others, this will maintains backwards compatibility with:
- `Iter` and `FindMut` were public, so now they are made generic, but they should be made to always use the `View` version in a breaking release
TODO: Add this to #494 when merging
>  SortedLinkedList: add SortedLinkedListView, similar to VecView on top of #486

- CHANGELOG.md
- src/linear_map.rs
- src/string/mod.rs
- src/vec/mod.rs
This enables them to be used in maps, especially with &str get values in a Map<String, T>.
Closes #478
> Impl Borrow and BorrowMut for String and Vec.

- src/binary_heap.rs
- src/linear_map.rs
- src/string/mod.rs
- src/vec/mod.rs
In 0.8.0 it was const, but this was removed in https://github.com/rust-embedded/heapless/pull/486, which would be an unexpected breaking change.
The other container types did not make the `capacity` method const, and therefore can kept with the normal name and the generic implementation.
No need for changelog for this change, since it affects b previous PR that has not been released.
> Keep `Vec::capacity` const

- src/deque.rs
Just noticed this while looking over the codebase.
> Fix minor mistake in `DequeInner` docs

- src/indexmap.rs
- src/mpmc.rs
- src/pool.rs
- src/spsc.rs
- src/string/mod.rs
Various documentation fixes for warnings shown by running `cargo clippy` and `typos`.
> Rustdoc clippy and typo fixes

- CHANGELOG.md
- src/deque.rs
These methods are equivalent to their `std` counterparts (except `swap_unchecked()`, which is a natural extension).
> Add `Deque::{swap, swap_unchecked, swap_remove_front, swap_remove_back}`

- src/lib.rs
- src/spsc.rs
- Some minor improvements for docs
- Fixed all the warnings for a plain build
- Suggest usage of static cell for initialization of Queue
> improvements for documentation

- CHANGELOG.md
- src/deque.rs
Fixes #520.
This PR implements the `PartialEq` and `Eq` traits for `Deque`. The implementation of the `PartialEq` was copied from the implementation for the [collection's `VecDeque`](https://doc.rust-lang.org/src/alloc/collections/vec_deque/mod.rs.html#2776).
> Implements PartialEq and Eq for Deque

- src/binary_heap.rs
- src/defmt.rs
- src/deque.rs
- src/histbuf.rs
- src/linear_map.rs
- src/ser.rs
- src/sorted_linked_list.rs
- src/string/mod.rs
- src/ufmt.rs
- src/vec/mod.rs
`MpMc` and `spsc::Queue` are not migrated to the new pattern because they were already invariant due to the `UnsafeCell`.
Fix #501
> Re-introduce covariance for containers

- src/binary_heap.rs
- src/deque.rs
- src/histbuf.rs
- src/indexmap.rs
- src/indexset.rs
- src/lib.rs
- src/pool/treiber/cas.rs
- src/sealed.rs
- src/spsc.rs
- src/string/mod.rs
- src/vec/mod.rs
- **Fix `clippy::use_self` warnings**
- **Fix `clippy::too_long_first_doc_paragraph` warnings**
- **Fix `clippy::redundant_pub_crate` warnings**
- **Fix `clippy::option_if_let_else` warnings**
See #535
> Fix `clippy::nursery` warnings

- CHANGELOG.md
- src/binary_heap.rs
- src/linear_map.rs
- src/string/mod.rs
- src/vec/mod.rs
See https://github.com/rust-embedded/heapless/issues/494
> `Vec`: rename `storage_capacity` to `capacity` and remove the `const` version

- src/lib.rs
This follows the C-QUESTION-MARK API guideline.
Also we had missed an unwrap on one of the push calls.
> lib.rs: remove unwrap from example

- src/linear_map.rs
This was previously required due to a false positive that has since been resolved.
> LinearMap: remove allow(clippy::map_identity)

- CHANGELOG.md
- src/lib.rs
- src/string/mod.rs
- src/ufmt.rs
- src/vec/mod.rs
Unit error types do not implement core::error::Error which leads to some ergonomic issues.
> Remove allow(clippy::result_unit_err)

- src/linear_map.rs
This tests that `LinearMap` can be indexed with a borrowed key, and implicitly tests that `String<N>` implements `Borrow<str>`.
> Add test for borrowed `LinearMap` key.

- src/binary_heap.rs
- src/defmt.rs
- src/deque.rs
- src/histbuf.rs
- src/lib.rs
- src/linear_map.rs
- src/mpmc.rs
- src/ser.rs
- src/sorted_linked_list.rs
- src/spsc.rs
- src/storage.rs
- src/string/mod.rs
- src/ufmt.rs
- src/vec/mod.rs
This makes `drain` usable in the context of an implementation generic over the storage
This also makes it possible to get a `*View` in this same context
This could also be a way to "de-monomorphize" all the implementations of the `Inner` structs:
We could make all implementation define an inner function that is over a `View` type, and start the
implementation with `this = self.as_(mut_)view`, maybe for binary size and compilation time benefits. For example the implementation of `VecInner::push` could be:
```rust
/// Appends an `item` to the back of the collection
///
/// Returns back the `item` if the vector is full.
pub fn push(&mut self, item: T) -> Result<(), T> {
fn inner<T>(this: &mut VecView<T>, item: T) -> Result<(), T> {
if this.len < this.storage_capacity() {
unsafe { …
```
> Implement `Vec::drain`, `as_(mut_)view` on the `*Inner` types, generic over `Storage`

- CHANGELOG.md
- src/indexmap.rs
This adds `truncate` method to `IndexMap`.
See corresponding [truncate](https://docs.rs/indexmap/latest/indexmap/map/struct.IndexMap.html#method.truncate) in the [indexmap](https://docs.rs/indexmap/latest/indexmap/index.html) crate.
Related pull requests:
* #525
> feat(indexmap): added `truncate`

- CHANGELOG.md
- src/indexmap.rs
- src/linear_map.rs
The old bounds were unnecessarily strict. This PR relaxes the `V: Eq` bound to `V: PartialEq`.
> Relax indexmap PartialEq bounds so value doesn't need to be Eq

- CHANGELOG.md
- src/indexmap.rs
This adds `get_index`, `get_index_mut` and `get_index_of` methods to `IndexMap`.
See corresponding [get_index](https://docs.rs/indexmap/latest/indexmap/map/struct.IndexMap.html#method.get_index), [get_index_mut](https://docs.rs/indexmap/latest/indexmap/map/struct.IndexMap.html#method.get_index_mut) and [get_index_of](https://docs.rs/indexmap/latest/indexmap/map/struct.IndexMap.html#method.get_index_of) in the [indexmap](https://docs.rs/indexmap/latest/indexmap/index.html) crate.
Related pull requests:
* #526
> feat(indexmap): added `get_index`, `get_index_mut` and `get_index_of`

- CHANGELOG.md
- Cargo.toml
- src/ufmt.rs
Most likely the compiler already inlines the function calls, but afaik adding the annotation makes it more likely.
I could not build it locally due to:
```
Compiling heapless v0.8.0 (/home/lucas/repos/heapless)
error[E0658]: use of unstable library feature 'build_hasher_simple_hash_one'
--> src/indexmap.rs:1260:28
|
1260 |     HashValue(build_hasher.hash_one(key) as u16)
|                            ^^^^^^^^
|
= note: see issue #86161 <https://github.com/rust-lang/rust/issues/86161> for more information
For more information about this error, try `rustc --explain E0658`.
error: could not compile `heapless` due to previous error
```
But the implementation seems trivial and has been tested elsewhere.
I did not add `uDisplay` for `Vec` because the formatting is not trivial.
We might want to …
> Add `uDisplay` for `String` and inline `ufmt` functions

- CHANGELOG.md
- Cargo.toml
- src/bytes.rs
- src/lib.rs
The [`Bytes`](https://crates.io/crates/bytes) crate traits are used quite a bit in the rust ecosystem. Implementing those traits can help bridge between `no_std` and `std` smoothly. Notably, [prost](https://crates.io/crates/prost) which is `no_std` deserialize using a BufMut.
> Add support for `Bytes`

- CHANGELOG.md
- src/sorted_linked_list.rs
- **Remove `sorted_linked_list::Iter` and `sorted_linked_list::IterInner`**
- **Remove `sorted_linked_list::FindMut` and `sorted_linked_list::FindMutInner`**
- **Introduce private `AsView` trait**
- **Update changelog**
See #494
> `SortedLinkedList`: Keep only the view versions of `Iter` and `FindMut`

- CHANGELOG.md
- src/binary_heap.rs
- src/de.rs
- src/defmt.rs
- src/indexmap.rs
- src/len_type.rs
- src/lib.rs
- src/linear_map.rs
- src/ser.rs
- src/string/mod.rs
- src/ufmt.rs
- src/vec/drain.rs
- src/vec/mod.rs
Currently, `Vec<T, N>` always uses `usize` for the length field, which leads to silly situations like `Vec<u8, 4>` being `8` bytes large on 32 bit platforms. This PR introduces a generic to provide this length field as well as a default for many common length values to avoid much user code changing.
I am okay to revert sections of this PR if wanted, such as
- ~~The change of `usize` to `LenT` in many arguments and return types, if they are considered too breaking.~~ Done, `usize` is still used for indexing and as the `len` return type.
- Adding the length generic to `VecView`, this can be changed to only store `usize` at the cost of only `Vec<T, N, usize>` being able to unsize (or requiring a `Vec::cast_len_type` call before unsizing, at least).
This lays the ground work for followup PRs …
> Implement a generic length parameter for Vec<T, N>

- CHANGELOG.md
- src/len_type.rs
- src/sorted_linked_list.rs
Part of #551.
The previous `SortedLinkedListIndex` seemed to store `Option<NonMaxLenT>` and required unsafe calls to get at the raw value without checking `::MAX`.... but none of those unsafe calls had safety comments and removing the unsafety shouldn't make the external interface unsound.
> Migrate SortedLinkedList to LenType

- CHANGELOG.md
- src/len_type.rs
- src/sorted_linked_list.rs
- src/string/mod.rs
- src/vec/mod.rs
If Vec has 0 capacity, it can store only 0 elements, so its len can be assumed to be always 0.
I'm updating `DefaultLenType` to have a special case: `DefaultLenType<0>` will be represented by zero sized type which always has value 0.
This allows reducing size of `heapless::Vec<u8, 0>` from 8 bytes to 0 bytes.
> Optimize size of heapless::Vec<_, 0> to 0 bytes

- CHANGELOG.md
- src/index_map.rs
Issue #559: `IndexMap::truncate` cleared the `entries`, but left dangling `indices`. This caused a `debug_assert` to fire if you searched for a key that had been truncated. Fixed by scanning the `indices` to remove the dangling ones, at the expense of making `truncate` O(n) instead of O(1). Added an assert to the doctest to catch this problem.
Fixes https://github.com/rust-embedded/heapless/issues/559.
> Fix #559: IndexMap::truncate leaves map in inconsistent state

- CHANGELOG.md
- build.rs
- src/pool.rs
- tests/tsan.rs
Only deny warnings on CI: https://rust-unofficial.github.io/patterns/anti_patterns/deny-warnings.html
Fix `pool::Arc` being enabled without atomics. 
Fixes https://github.com/rust-embedded/heapless/issues/463.
> Fix `pool::Arc` being enabled without atomics. 

- CHANGELOG.md
- Cargo.toml
- src/lib.rs
- src/spsc.rs
This allows constructing a producer-consumer pair directly in a `static`, e.g.
```rust
static PC: Mutex<RefCell<(Option<Producer<'static, (), 4>>, Option<Consumer<'static, (), 4>>)>> = {
static mut Q: Queue<(), 4> = Queue::new();
let (p, c) = unsafe { Q.split() };
Mutex::new(RefCell::new((Some(p), Some(c))))
};
```
> Make `Queue::split` `const`.

- CHANGELOG.md
- src/history_buf.rs
- src/index_map.rs
- src/spsc.rs
- src/string/mod.rs
- src/vec/mod.rs
- tests/tsan.rs
Looks like there are some new clippy issues. This is the result of running with `--fix`
> Apply clippy fixes

- src/binary_heap.rs
- src/deque.rs
- src/vec/mod.rs
I believe these names are better because they are more consistent with
the naming of their non-mutable siblings and also with the general
conventions in the Rust world.
> Better names for method returning mutable references

- CHANGELOG.md
- Cargo.toml
I think these should be merged first
> Prepare release 0.9.1

- .github/workflows/build.yml
- CHANGELOG.md
- Cargo.toml
- README.md
- **Formatting fixes to Cargo.toml**
- **Declare MSRV in Cargo.toml**
- **Run a job against MSRV**
> Make MSRV explicit & check accidental bump in the CI

- CHANGELOG.md
- src/lib.rs
Arc was added twice, evidently a copy-paste bug.
It does not appear that anything else is missing, so I just removed the duplicate line.
> Remove duplicate documentation line

- .github/workflows/build.yml
- CHANGELOG.md
- Cargo.toml
- src/binary_heap.rs
- src/c_string.rs
- src/deque.rs
- src/history_buf.rs
- src/index_map.rs
- src/index_set.rs
- src/len_type.rs
- src/lib.rs
- src/linear_map.rs
- src/sorted_linked_list.rs
- src/string/mod.rs
- src/vec/mod.rs
Implements zeroization support across all heapless data structures to securely clear sensitive data from memory:
- Added Zeroize trait implementations for `Vector`, `CString`, `String`, `IndexMap`, `IndexSet`, and other structures
- Created tests verifying proper zeroization behavior for each structure
- Added necessary documentation
This feature is essential for security-sensitive applications needing to prevent data leaks from memory dumps.
Note: Zeroize initially worked on `Vector` purely via derivation, however was not complete without proper bound checks. Without these checks, the `deref` implementation of Zeroize was used instead, which led to incomplete zeroization of the Vector's contents.
> Add zeroization support for heapless data structures

- CHANGELOG.md
- src/linear_map.rs
I've made `linear_map` public as a namespace for `linear_map::Entry`. There could be a bit of confusion with the `crate::Entry` re-export of `index_map::Entry`, not sure if there's any better option.
Closes #471
> Add LinearMap entry() and retain()
