ci/script.sh, src/ring_buffer/mod.rs, src/ring_buffer/spsc.rs, tests/tsan.rs
This needs to be fixed before the next release
Interestingly I see that the test passes when compiled without optimizations but fails when
optimized. Perhaps there's some UB in here.
cc @pftbest
=> add contention test

src/ring_buffer/spsc.rs, tests/tsan.rs
Is speedup from one less barrier worth the risk in this case?
=> What if tsan is right?

.travis.yml, src/vec.rs
=> impl Debug, PartialEq & Eq

src/lib.rs, src/string.rs, src/vec.rs
And a cleanup commit removing unused `#![features]`
=>  Add AsMut and AsRef implementations for Vec and String 

CHANGELOG.md, Cargo.toml, src/__core.rs, src/binary_heap.rs, src/cfail.rs, src/lib.rs, src/linear_map.rs, src/ring_buffer/mod.rs, src/ring_buffer/spsc.rs, src/string.rs, src/vec.rs, tests/tsan.rs
=> drop untagged-option dependency, and depend on generic-array

.travis.yml
=> CI: run tests on stable

src/string.rs, src/vec.rs
=> impl Hash for Vec and String

Cargo.toml, ci/script.sh, src/de.rs, src/lib.rs, src/ser.rs
This PR introduces complete serialization and deserialization support for all data structures in this crate. Fixes #58.
=> Serde support

src/binary_heap.rs, src/linear_map.rs, src/string.rs, src/vec.rs
As pointed out in #56 
The implementation for Queue is missing, as it would be opinionated about the atomic size to use and whether it is a single or multi core variant.
=> Implement Default for Vec, String, LinearMap, BinaryHeap

src/spsc/mod.rs
=> Implement Hash for Queue

src/spsc/mod.rs
=> Implement PartialEq and Eq for Queue

src/spsc/mod.rs
=> Implement Clone for Queue

src/indexmap.rs
=> Implement Eq and PartialEq for Indexmap

src/binary_heap.rs
As discussed in https://github.com/japaric/heapless/issues/109, please have a look and lets bike-shed the API.
=> Added peek_mut for the binary heap

CHANGELOG.md, Cargo.toml
=> Prepared for 0.5.1 release

src/spsc/mod.rs
The implementation is pretty straightforward and it's useful
=> Add DoubleEndedIterator to queue iterators

.travis.yml, build.rs, no-atomics.sh, no-cas.sh, src/i.rs, src/lib.rs, src/mpmc.rs, src/pool/mod.rs, src/sealed.rs, src/spsc/mod.rs
=> remove spsc / pool / mpmc modules on targets w/o atomic / CAS support

src/vec.rs
=> Implement Vec::from_slice

CHANGELOG.md, Cargo.toml
Prepared v0.5.5 to release the latest accepted PRs
=> Preparing for v0.5.5

README.md
It took me some time to figure out which features must be used for tests. So this pull request removes some friction.
=> readme: add instructions for tests

src/histbuf.rs, src/lib.rs, src/ufmt.rs, tests/cpass.rs
Preparation for new CI where cargo fmt will be a part
=> Cargo format

.github/bors.toml, .github/workflows/build.yml, .github/workflows/properties/build.properties.json
The test named `testtsan` fails with a 
```
WARNING: ThreadSanitizer: data race (pid=2180)
```
This seems to be a known issue? What would you suggest?
=> First GitHub Actions test

src/pool/singleton.rs
This gives `mem::forget` functionality on `P::Data` contained within the box, rather than the box itself.
=> Implement Box::forget for the singleton pool

src/pool/mod.rs, src/pool/singleton.rs
@korken89  I removed `AsSlice` in #200 but did not propose alternative. Sorry.
=> AsRef, AsMut for pool

src/vec.rs
With the addition of this method, `heapless::Vec` can be used to safely and easily create an array one element at a time.
I don't have much experience with `MaybeUninit`, so please double check my implementation.
=> Add new `Vec::into_array` method

CHANGELOG.md, Cargo.toml, src/histbuf.rs, src/lib.rs, src/mpmc.rs, src/sealed.rs, src/spsc.rs, src/vec.rs
=> Preparing v0.7.2

CHANGELOG.md, Cargo.toml, src/pool/singleton.rs, src/spsc.rs
=> Deprecate `Box::freeze`, prepare v0.7.3

src/lib.rs, src/sealed.rs, src/sorted_linked_list.rs
A linked list priority queue, similar to binary heap.
Has different useful properties.
=> Added sorted linked list implementation

src/mpmc.rs, src/sealed.rs
Fixes #243
N must also be at least 2
=> Fix MPMC size asserts

CHANGELOG.md, Cargo.toml, src/defmt.rs
This seems to solve the issue of supporting both defmt versions
=> defmt version range

CHANGELOG.md, Cargo.toml, src/indexmap.rs, src/indexset.rs
=> Fix bounds in IndexMap and IndexSet, IndexSet::new() is now const

CHANGELOG.md, src/pool/mod.rs
* Pool trait and exception use missing
=> pool: fix example

src/indexmap.rs
I ran up against some problems trying to consume Indexmaps. 
Fairly low-effort implementation of IntoIter maybe ordering should be commented but I think that when iterating over a map ordering can be assumed to be _implementation specific_ and not promising an ordering is better for future implementation flexibility.
=> Add intoiter for Indexmap

CHANGELOG.md, src/indexmap.rs, src/indexset.rs
=> add first/last API to IndexMap and IndexSet

CHANGELOG.md, src/deque.rs
=> make Deque::pop_{front,back}_unchecked public

tests/tsan.rs
the feature has been stabilized in a recent nightly
=> remove the scoped_threads feature gate

cfail/ui/not-send.stderr
should fix CI and unblock PRs like #317
=> update compile_fail test to work on 1.64

CHANGELOG.md, Cargo.toml
cleaned up version of PR #313 
closes #313
=> switch to a more recent atomic-polyfill that compiles for AVR

src/indexmap.rs, src/indexset.rs
=> clarify the iteration order of IndexMap / IndexSet

src/spsc.rs
=> spsc::Queue: make example less unsafe

CHANGELOG.md, src/indexmap.rs, src/indexset.rs
Needed to remove IndexMap/IndexSet elements while iterating over it.
=> Implement retain for IndexSet/IndexMap.

cfail/ui/freeze.stderr, cfail/ui/not-send.stderr
Fixes the `cfail` CI job.
Will still fail until #383 is resolved.
=> Update UI tests

Cargo.toml
Changelog skipped, this is just a development dep for testing the `ufmt-write` impl.
=> ufmt: 0.1 -> 0.2

CHANGELOG.md, src/string.rs
Accidentally deleted the branch when rebasing #395
=> string: replace From<&str> with TryFrom<&str>

src/de.rs, src/ser.rs
Implement `serde::Serialize` and `serde::Deserialize` for `Deque<T, N>`.
=> Implement #367

.github/workflows/build.yml, Cargo.toml, cfail/Cargo.toml, src/binary_heap.rs, src/indexmap.rs, src/indexset.rs, src/lib.rs, src/pool/arc.rs, src/pool/boxed.rs, src/pool/object.rs, src/string.rs, src/vec.rs
* Also fixes `docs.rs` builds because `--all-features` no longer works
* Also adds `doc_auto_cfg` for `docs.rs` builds because we have a lot of features
=> docs: modernize intra doc links

CHANGELOG.md, Cargo.toml
Also sneaking in a minor portable-atomic fix.
=> Release v0.8.0

CHANGELOG.md, src/pool/arc.rs, src/pool/object.rs
Closes #411 hopefully for the last time.
=> Fix clippy lints in arc_pool and object_pool

tests/tsan.rs
=> Fix tsan.rs CI errors

CHANGELOG.md, src/vec.rs
=> Add spare_capacity_mut

CHANGELOG.md, src/deque.rs
A simple change that should be self-explanatory. If more comments, etc. are needed then please let me know.
=> Impl Extend for Deque

.gitattributes, CHANGELOG.md, src/de.rs, src/ser.rs
Added `serde::Serialize` and `serde::Deserialize` implementations to `HistoryBuffer`.
=> Add serde implementations to HistoryBuffer

src/lib.rs
See https://github.com/rust-embedded/heapless/pull/500#discussion_r2029972717
=> Add FIXME prefix to temporary workaround

src/mpmc.rs, src/spsc.rs
Closes https://github.com/rust-embedded/heapless/issues/466.
=> Clean up queue docs.

.github/workflows/build.yml, CHANGELOG.md, src/bytes.rs
Closes https://github.com/rust-embedded/heapless/issues/566.
=> Fix `bytes` feature.

CHANGELOG.md, src/lib.rs
Fix https://github.com/rust-embedded/heapless/issues/601
=> Implement default for capacity error
